package gui;

import core.Licencia;
import java.awt.Color;
import java.awt.Image;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JLabel;



public class Proyecto extends javax.swing.JFrame {
    Licencia objLicencia;
    public Proyecto() {
        initComponents();
        jTabbedPane2.setEnabledAt(1, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Sexo = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtApP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCURP = new javax.swing.JTextField();
        rbtnMasculino = new javax.swing.JRadioButton();
        rbtnMasculona = new javax.swing.JRadioButton();
        txtUsuario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtApM = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        guardarDatos = new javax.swing.JButton();
        validarNombre = new javax.swing.JLabel();
        lblValidarApP = new javax.swing.JLabel();
        lblValidarApM = new javax.swing.JLabel();
        txtFecha_nacimiento = new com.toedter.calendar.JDateChooser();
        lblValidarEdad = new javax.swing.JLabel();
        lblValidarNacimiento = new javax.swing.JLabel();
        lblValidarCurp = new javax.swing.JLabel();
        lblValidarSexo = new javax.swing.JLabel();
        lblValidarUsuario = new javax.swing.JLabel();
        lblValidarContrasenia = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<String>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        fechaRegistro = new com.toedter.calendar.JDateChooser();
        fechaVencimiento = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        panelCamara = new JPanelWebCam.JPanelWebCam();
        jPanel5 = new javax.swing.JPanel();
        lblNombreD = new javax.swing.JLabel();
        lblNacimientoD = new javax.swing.JLabel();
        lblEdadD = new javax.swing.JLabel();
        lblCURPD = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        dlblNombreD = new javax.swing.JLabel();
        dlblNacimientoD = new javax.swing.JLabel();
        dlblEdadD = new javax.swing.JLabel();
        dlblCURPD = new javax.swing.JLabel();
        dlblSexoD = new javax.swing.JLabel();
        dlblUsuarioD = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        tituloCaptura = new javax.swing.JLabel();
        btnTomarFoto = new javax.swing.JButton();
        lblIndicacion = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setName("jtpPestanias"); // NOI18N

        jPanel2.setName("jpnPanel"); // NOI18N

        jLabel2.setText("Nombre:");

        jLabel3.setText("Edad:");

        jLabel4.setText("CURP:");

        jLabel1.setText("Usuario:");

        txtNombre.setName("txtNombre"); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        jLabel5.setText("Apellido Paterno:");

        txtApP.setName("txtApP"); // NOI18N
        txtApP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApPKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApPKeyTyped(evt);
            }
        });

        jLabel6.setText("Apellido Materno:");

        txtEdad.setName("txtEdad"); // NOI18N
        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadKeyTyped(evt);
            }
        });

        jLabel7.setText("Fecha de Nacimiento:");

        jLabel8.setText("Sexo:");

        txtCURP.setName("txtCURP"); // NOI18N
        txtCURP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCURPKeyTyped(evt);
            }
        });

        Sexo.add(rbtnMasculino);
        rbtnMasculino.setText("M");

        Sexo.add(rbtnMasculona);
        rbtnMasculona.setText("F");

        txtUsuario.setName("txtUsuario"); // NOI18N

        jLabel9.setText("Password:");

        txtApM.setName("txtApM"); // NOI18N
        txtApM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApMKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApMKeyTyped(evt);
            }
        });

        txtPass.setName("pwrUsuario"); // NOI18N

        guardarDatos.setText("Guardar");
        guardarDatos.setName("btnGuardar"); // NOI18N
        guardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarDatosActionPerformed(evt);
            }
        });

        lblValidarEdad.setText("jLabel18");

        lblValidarNacimiento.setText("jLabel18");

        lblValidarCurp.setText("jLabel18");

        lblValidarSexo.setText("jLabel18");

        lblValidarUsuario.setText("jLabel18");

        lblValidarContrasenia.setText("jLabel18");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtNombre)
                                            .addComponent(txtCURP, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                            .addComponent(lblValidarCurp, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(guardarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                                    .addComponent(jLabel8)
                                                                    .addGap(16, 16, 16)
                                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lblValidarSexo)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                            .addComponent(rbtnMasculino)
                                                                            .addGap(18, 18, 18)
                                                                            .addComponent(rbtnMasculona))))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                                    .addComponent(jLabel9)
                                                                    .addGap(18, 18, 18)
                                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lblValidarContrasenia)
                                                                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel7)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(lblValidarNacimiento)
                                                            .addComponent(txtFecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(180, 180, 180))))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(txtApP, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel6))
                                                    .addComponent(lblValidarApP))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(lblValidarApM)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addComponent(txtApM)))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(validarNombre)
                                            .addComponent(lblValidarEdad))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValidarUsuario)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtApP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtApM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(validarNombre)
                    .addComponent(lblValidarApP)
                    .addComponent(lblValidarApM))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValidarEdad)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(txtCURP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnMasculino)
                            .addComponent(rbtnMasculona))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValidarCurp)
                            .addComponent(lblValidarSexo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValidarUsuario)
                            .addComponent(lblValidarContrasenia))
                        .addGap(8, 8, 8)
                        .addComponent(guardarDatos))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtFecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValidarNacimiento)))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Datos", jPanel2);

        jLabel10.setText("NoControl:");

        jLabel11.setText("Tipo de Licencia:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chófer", "Automovilista", "Motociclista" }));

        jLabel12.setText("Fecha de Registro:");

        jLabel13.setText("Vigencia:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "3", "5" }));

        jLabel14.setText("Vencimiento:");

        jLabel15.setText("Nombre de contacto en caso de Emergencia:");

        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField12KeyTyped(evt);
            }
        });

        jLabel16.setText("No Telefono:");

        jTextField13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField13KeyTyped(evt);
            }
        });

        jLabel17.setText("Observaciones:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fechaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(fechaVencimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField12)
                            .addComponent(jTextField13)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(346, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fechaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(fechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Licencia", jPanel3);

        panelCamara.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 3));

        javax.swing.GroupLayout panelCamaraLayout = new javax.swing.GroupLayout(panelCamara);
        panelCamara.setLayout(panelCamaraLayout);
        panelCamaraLayout.setHorizontalGroup(
            panelCamaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelCamaraLayout.setVerticalGroup(
            panelCamaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));

        lblNombreD.setText("Nombre completo:");

        lblNacimientoD.setText("Fecha de nacimiento:");

        lblEdadD.setText("Edad:");

        lblCURPD.setText("CURP:");

        lblSexo.setText("Sexo:");

        lblUsuario.setText("Usuario:");

        dlblNombreD.setText("jLabel18");

        dlblNacimientoD.setText("jLabel18");

        dlblEdadD.setText("jLabel18");

        dlblCURPD.setText("jLabel18");

        dlblSexoD.setText("jLabel19");

        dlblUsuarioD.setText("jLabel19");

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setMaximumSize(new java.awt.Dimension(110, 130));
        jPanel6.setPreferredSize(new java.awt.Dimension(100, 50));

        lblFoto.setMaximumSize(new java.awt.Dimension(100, 100));
        lblFoto.setMinimumSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreD)
                    .addComponent(lblNacimientoD)
                    .addComponent(lblEdadD)
                    .addComponent(lblCURPD)
                    .addComponent(lblSexo)
                    .addComponent(lblUsuario))
                .addGap(54, 54, 54)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dlblUsuarioD)
                    .addComponent(dlblSexoD)
                    .addComponent(dlblCURPD)
                    .addComponent(dlblEdadD)
                    .addComponent(dlblNacimientoD)
                    .addComponent(dlblNombreD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreD)
                            .addComponent(dlblNombreD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNacimientoD)
                            .addComponent(dlblNacimientoD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEdadD)
                            .addComponent(dlblEdadD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCURPD)
                            .addComponent(dlblCURPD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSexo)
                            .addComponent(dlblSexoD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsuario)
                            .addComponent(dlblUsuarioD))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                .addGap(89, 89, 89))
        );

        tituloCaptura.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tituloCaptura.setForeground(new java.awt.Color(204, 0, 51));
        tituloCaptura.setText("Republica Amorosa! Amo a Melina-chan");

        btnTomarFoto.setBackground(new java.awt.Color(255, 51, 51));
        btnTomarFoto.setForeground(new java.awt.Color(255, 255, 255));
        btnTomarFoto.setText("Capturar foto");
        btnTomarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTomarFotoActionPerformed(evt);
            }
        });

        lblIndicacion.setText("Click sobre el cuadro azul para iniciar la camara");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tituloCaptura)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTomarFoto)
                                .addGap(67, 67, 67))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(lblIndicacion)
                                        .addGap(0, 74, Short.MAX_VALUE))
                                    .addComponent(panelCamara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloCaptura)
                    .addComponent(lblIndicacion))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(panelCamara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTomarFoto)
                        .addGap(0, 7, Short.MAX_VALUE))))
        );

        jTabbedPane2.addTab("Captura de Foto", jPanel4);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApPKeyTyped
        // TODO add your handling code here:
        char validar =evt.getKeyChar();
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtApPKeyTyped

    private void txtApMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApMKeyTyped
        // TODO add your handling code here:
        char validar =evt.getKeyChar();
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtApMKeyTyped

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
        // TODO add your handling code here:
        char validar =evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtEdadKeyTyped

    private void txtCURPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCURPKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCURPKeyTyped

    private void jTextField13KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField13KeyTyped
        // TODO add your handling code here:
        char validar =evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField13KeyTyped

    private void jTextField12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyTyped
        // TODO add your handling code here:
        char validar =evt.getKeyChar();
        if(Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextField12KeyTyped

    private void guardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarDatosActionPerformed
        validarSexo();
        validarCurp();
        validarUsuario();
        isValidoNombres(txtNombre.getText(), validarNombre);
        isValidoNombres(txtApP.getText(), lblValidarApP);
        isValidoNombres(txtApM.getText(), lblValidarApM);
        validarContraseña();
        validarFecha();
        validarEdad();
        if(validarSexo() 
                && validarCurp()
                && validarUsuario()
                && isValidoNombres(txtNombre.getText(), validarNombre)
                && isValidoNombres(txtApP.getText(), lblValidarApP)
                && isValidoNombres(txtApM.getText(), lblValidarApM)
                && validarContraseña()
                && validarFecha()
                && validarEdad()) {
            
            //Crea el objeto y asigna datos
            objLicencia= new Licencia();
            objLicencia.setNombre(txtNombre.getText());
            objLicencia.setApellidoPaterno(txtApP.getText());
            objLicencia.setApellidoMaterno(txtApM.getText());
            objLicencia.setEdad(Integer.parseInt(txtEdad.getText()));
            //Nacimiento
            objLicencia.setCURP(txtCURP.getText());
            objLicencia.setSexo(obtenerSexo());
            objLicencia.setUsuario(txtUsuario.getText());
            objLicencia.setContraseña(txtPass.getText());
            
            
            System.out.println("Todo bien");
            jTabbedPane2.setEnabledAt(1, true);
            llenarDatosPersonales();
        }
        else System.out.println("Error");
    }//GEN-LAST:event_guardarDatosActionPerformed

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        isValidoNombres(txtNombre.getText(), validarNombre);
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtApPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApPKeyReleased
        isValidoNombres(txtApP.getText(), lblValidarApP);
    }//GEN-LAST:event_txtApPKeyReleased

    private void txtApMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApMKeyReleased
        isValidoNombres(txtApM.getText(), lblValidarApM);
    }//GEN-LAST:event_txtApMKeyReleased

    private void btnTomarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTomarFotoActionPerformed
        Image foto = panelCamara.getImage();
        ImageIcon fotoIcon = new ImageIcon(foto.getScaledInstance(140, 135, Image.SCALE_SMOOTH));
        lblFoto.setIcon(fotoIcon);
    }//GEN-LAST:event_btnTomarFotoActionPerformed
    
    private boolean validarCurp(){
        String regex = "[A-Z]{1}[AEIOU]{1}[A-Z]{2}[0-9]{2}" +
            "(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])" +
            "[HM]{1}" +
            "(AS|BC|BS|CC|CS|CH|CL|CM|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)" +
            "[B-DF-HJ-NP-TV-Z]{3}" +
            "[0-9A-Z]{1}[0-9]{1}$";
        String curp = txtCURP.getText();
        Pattern patron = Pattern.compile(regex);
        if(curp.equals("")){
            lblValidarCurp.setForeground(Color.red);
            lblValidarCurp.setText("Debe llenar este campo");
            return false;
        }
        else{
            lblValidarCurp.setText("");
            if(!patron.matcher(curp).matches()){
                 lblValidarCurp.setText("Debe introducir CURP valido");
                return false;
            }
            else{
                lblValidarCurp.setText("");
                return true;
            }
        }
    }
    private boolean isValidoNombres(String cadena, JLabel lblModificar){
        if(cadena.equals("")){
            lblModificar.setForeground(Color.red);
            lblModificar.setText("Debe llenar este campo");
            return false;
        }
        else if(!cadena.matches("[A-Z].*")) {
            lblModificar.setForeground(Color.red);
            lblModificar.setText("Se debe iniciar con Mayuscula");
            return false;
        }
        else if(!cadena.matches("[^0-9]*")) {
            lblModificar.setForeground(Color.red);
            lblModificar.setText("No debe incluir numeros el nombre");
            return false;
        }
        else if(!cadena.matches("[A-Z][a-z]*")) {
            lblModificar.setForeground(Color.red);
            lblModificar.setText("La primera letra solamente debe ser mayuscula, "
                + "los demas deben de ser minusculas");
            return false;
        }
        else if(!cadena.equals("")){
            lblModificar.setText("");
            return  true;
        }
        else if(cadena.matches("[A-Z].*")) {
            lblModificar.setText("");
            return  true;
        }
        else if(cadena.matches("[^0-9]*")) {
            lblModificar.setText("");
            return  true;
        }
        else if(cadena.matches("[A-Z][a-z]*")) {
            lblModificar.setText("");
            return  true;
        }
        return  true;
    }
    private boolean validarEdad(){
        if(txtEdad.getText().equals("")){
            lblValidarEdad.setForeground(Color.red);
            lblValidarEdad.setText("Necesita llenar este campo");
            return false;
        }else{
            //Edad valido > 18 y < 120
            lblValidarEdad.setText("");
            return true;
        }
    }
    private boolean validarUsuario(){
        String cadena = txtUsuario.getText();
        String regex = "^(?=\\w*\\d)(?=\\w*[A-Z])(?=\\w*[a-z])\\S{3,}$";
        if(cadena.equals("")){
            lblValidarUsuario.setForeground(Color.red);
            lblValidarUsuario.setText("Debe introducir un nombre de usuario");
            return false;
        }else{
            lblValidarUsuario.setText("");
            if(!cadena.matches(regex)){
                lblValidarUsuario.setForeground(Color.red);
                lblValidarUsuario.setText("El usuario debe contener mayusculas \n minusculas y numeros");
                return false;
            }else{
                lblValidarUsuario.setText("");
                return true;
            }
        }
    }
    private boolean validarContraseña(){
        String regex = "^(?=\\w*\\d)(?=\\w*[A-Z])(?=\\w*[a-z])\\S{8,}$";
        String cadena =txtPass.getText();
        if(cadena.equals("")){
            lblValidarContrasenia.setForeground(Color.red);
            lblValidarContrasenia.setText("Debe llenar este campo");
            return false;
        }else{
            lblValidarContrasenia.setText("");
            if(!cadena.matches(regex)){
                lblValidarContrasenia.setForeground(Color.red);
                lblValidarContrasenia.setText("La contraseña debe contener mayusculas \n minusculas y numeros y mayor a 8 caracteres");
                return false;
            }
            else{
                lblValidarContrasenia.setText("");
                return true;
            }
        }
    }
    private boolean validarSexo(){
        if(!rbtnMasculino.isSelected() && !rbtnMasculona.isSelected()){
            lblValidarSexo.setForeground(Color.red);
            lblValidarSexo.setText("Selecciona un sexo");
            return false;
        }else{
            lblValidarSexo.setText("");
            return true;
        }
    }
    private boolean validarFecha(){
        if(txtFecha_nacimiento.getDate()==null){
            lblValidarNacimiento.setForeground(Color.red);
            lblValidarNacimiento.setText("Selecciona una fecha de nacimiento plis!");
            return false;
        }else{
            lblValidarNacimiento.setText("");
            return true;
        }
    }
    private void desctivarCamposDatos(){
        txtNombre.disable();
    }
    private String obtenerSexo(){
        if(rbtnMasculino.isSelected()) return "M";
        else return "F";
    }
    private void llenarDatosPersonales(){
        dlblNombreD.setText(objLicencia.getNombre() + " " + objLicencia.getApellidoPaterno()
        + " " + objLicencia.getApellidoMaterno());
        dlblEdadD.setText(objLicencia.getEdad() + "");
        dlblCURPD.setText(objLicencia.getCURP());
        dlblSexoD.setText(objLicencia.getSexo());
        dlblUsuarioD.setText(objLicencia.getUsuario());
    }
    
    /*
    private boolean validarVacios(){
        boolean bandera = false;
        if(validarCamposVacios(txtNombre.getText(), validarNombre)
                || validarCamposVacios(txtApP.getText(), lblValidarApP)
                || validarCamposVacios(txtApM.getText(), lblValidarApM)
                || validarCamposVacios(txtCURP.getText(), lblValidarCurp)
                || validarCamposVacios(txtEdad.getText(), lblValidarEdad)
                //&& validarCamposVacios(txtFecha_nacimiento.getDate().toString(), lblValidarNacimiento)
                || validarCamposVacios(txtUsuario.getText(), lblValidarUsuario)
                || validarCamposVacios(txtPass.getText(), lblValidarContrasenia)
                || validarSexo()){
            System.out.println("Hay campos vacios");
            
        }
        return bandera;
    }
    */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.ButtonGroup Sexo;
    private javax.swing.JButton btnTomarFoto;
    private javax.swing.JLabel dlblCURPD;
    private javax.swing.JLabel dlblEdadD;
    private javax.swing.JLabel dlblNacimientoD;
    private javax.swing.JLabel dlblNombreD;
    private javax.swing.JLabel dlblSexoD;
    private javax.swing.JLabel dlblUsuarioD;
    private com.toedter.calendar.JDateChooser fechaRegistro;
    private com.toedter.calendar.JDateChooser fechaVencimiento;
    private javax.swing.JButton guardarDatos;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblCURPD;
    private javax.swing.JLabel lblEdadD;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblIndicacion;
    private javax.swing.JLabel lblNacimientoD;
    private javax.swing.JLabel lblNombreD;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblValidarApM;
    private javax.swing.JLabel lblValidarApP;
    private javax.swing.JLabel lblValidarContrasenia;
    private javax.swing.JLabel lblValidarCurp;
    private javax.swing.JLabel lblValidarEdad;
    private javax.swing.JLabel lblValidarNacimiento;
    private javax.swing.JLabel lblValidarSexo;
    private javax.swing.JLabel lblValidarUsuario;
    private JPanelWebCam.JPanelWebCam panelCamara;
    private javax.swing.JRadioButton rbtnMasculino;
    private javax.swing.JRadioButton rbtnMasculona;
    private javax.swing.JLabel tituloCaptura;
    private javax.swing.JTextField txtApM;
    private javax.swing.JTextField txtApP;
    private javax.swing.JTextField txtCURP;
    private javax.swing.JTextField txtEdad;
    private com.toedter.calendar.JDateChooser txtFecha_nacimiento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JLabel validarNombre;
    // End of variables declaration//GEN-END:variables
    private ImageIcon succes = new ImageIcon("src/img/succes.png");
  
}
